### ISSUE TITLE
1.0.2 > movement issue

### ISSUE THREAD

**Issue by Andiweli** [JetStreamSham/ZGloom-vita#8] opened 2021-08-24 09:05 UTC
Hey one last thing... think it has something to do with the right analog stick I made the pull request earlier:

When strifing left or right, the player can't rotate left or right.
- For example if your strife right, you can rotate left, but NOT right.
- Same for left.

Perhaps you can fix that too.
Rest seem to work perfect :) Great work!!!

**Comment by JetStreamSham** [comment] 2021-08-24 09:55
ZGloom for the PC has the same behaviour, I do not know if it is bug or intended behaviour.
However this is only occurs for the strafe and rotation key, strafing while using the mouse to rotate works.
Fixed in https://github.com/JetStreamSham/ZGloom-vita/commit/aa167489e633f8620a3c7db096a55ada22928acb

**Comment by Andiweli** [comment] 2021-08-24 10:09
Working perfect! I'll have to thank you so much.
Are you on Discord or so?

**Comment by JetStreamSham** [comment] 2021-08-24 11:06
My discord name is JetStream#6420

**Comment by Andiweli** [comment] 2021-08-24 19:25
Fixed and working as expected.

**Closed as completed** 2021-08-24 19:25 UTC
